# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breastCancerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breatcancerinformationitem',
            options={'verbose_name_plural': '乳腺癌信息'},
        ),
        migrations.AddField(
            model_name='breatcancerinformationitem',
            name='SubjectTypeItemDescription',
            field=models.TextField(default=1, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breatcancerinformationitem',
            name='SubjectTypeItemDetailDescription',
            field=models.TextField(default=1, verbose_name='详细描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breatcancerinformationitem',
            name='SubjectTypeItemDisplaySequence',
            field=models.IntegerField(default=1, verbose_name='排序权重(数字)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breatcancerinformationitem',
            name='foreign_Key',
            field=models.ForeignKey(default='BreatCancerInformation', editable=False, on_delete=django.db.models.deletion.CASCADE, to='breastCancerApp.BreatCancerSubject', verbose_name='外键'),
        ),
    ]
