# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breastCancerApp', '0002_auto_20160507_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breatcancerinformationitem',
            old_name='SubjectTypeItemDescription',
            new_name='subjectTypeItemDescription',
        ),
        migrations.RenameField(
            model_name='breatcancerinformationitem',
            old_name='SubjectTypeItemDetailDescription',
            new_name='subjectTypeItemDetailDescription',
        ),
        migrations.RenameField(
            model_name='breatcancerinformationitem',
            old_name='SubjectTypeItemDisplaySequence',
            new_name='subjectTypeItemDisplaySequence',
        ),
        migrations.RenameField(
            model_name='breatcancerinformationitem',
            old_name='SubjectTypeItemName',
            new_name='subjectTypeItemName',
        ),
        migrations.RemoveField(
            model_name='breatcancerinformationitem',
            name='foreign_Key',
        ),
        migrations.DeleteModel(
            name='BreatCancerSubject',
        ),
    ]
