# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breastCancerApp', '0003_auto_20160508_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=30, verbose_name='主题名称')),
                ('subjectDescription', models.TextField(verbose_name='描述')),
                ('subjectDisplaySequence', models.IntegerField(verbose_name='排序权重(数字)')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectItemName', models.CharField(max_length=30, verbose_name='子标题名称')),
                ('subjectItemDescription', models.TextField(verbose_name='描述')),
                ('subjectItemDetailDescription', models.TextField(verbose_name='详细描述')),
                ('subjectItemDisplaySequence', models.IntegerField(verbose_name='排序权重(数字)')),
                ('foreign_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breastCancerApp.Subject', verbose_name='外键')),
            ],
        ),
        migrations.DeleteModel(
            name='BreatCancerInformationItem',
        ),
    ]
