# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breastCancerApp', '0006_auto_20160508_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectitem',
            name='foreign_Key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breastCancerApp.Subject', verbose_name='外键'),
        ),
    ]
